Recognize start of an Elvish statement
ALSchwalm/elvish-mode pull request #3
Opened 2017-07-24 11:40 UTC by zzamboni

Added `elvish-start-of-statement` definition and use it to recognize
keywords and functions, this improved highlighting and allows to
add the arithmetic/comparison functions again without spurious
highlighting.

2017-07-24 11:41 UTC, zzamboni commented
@ALSchwalm with this patch the arithmetic/comparison characters are no longer being highlighted when they are part of some other command/statement, but for some reason they are also not highlighted at the beginning of a statement - not sure why (other keywords are highlighted correctly). Any ideas?

2017-07-24 21:25 UTC, ALSchwalm requested changes

2017-07-24 21:25 UTC, ALSchwalm commented on elvish-mode.el
> +    (eval `(rx ,elvish-start-of-statement (group ,keywords) symbol-end)))
Using this for keywords breaks highlighting on things like:

    if (== $foo $bar) {
        ...
    } else {    # the else is not highlighted
        ...
    }

You could probably add '}' to the `elvish-start-of-statement` definition, but I don't think I see why a keyword should have to occur after a statement start. That may be generally true right now, but I would think keywords could appear anywhere in principle. Do you have a case where keyword highlighting is wrong with the current pattern?

2017-07-25 08:10 UTC, zzamboni commented on elvish-mode.el
> +    (eval `(rx ,elvish-start-of-statement (group ,keywords) symbol-end)))
My main motivation was to allow proper highlighting of the arithmetic and comparison functions. And you are right that in principle a keyword can appear anywhere - *but* a function can only appear at the start of a statement. How about I remove the `elvish-start-of-statement` from the keyword highlighting pattern, and leave it only for functions?

2017-07-25 21:50 UTC, ALSchwalm approved these changes

2017-07-25 21:50 UTC, merged

2017-07-25 21:50 UTC, ALSchwalm commented
Looks good to me. Thanks for the PR